spring.datasource.url=jdbc:postgresql://localhost:5433/finsight
spring.datasource.username=postgres
spring.datasource.password=piyu1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yRmluU2lnaHRKV1RUb2tlbnNNdXN0QmU2NEJ5dGVz
app.jwt.expiration-ms=86400000
